#!/bin/sh

#Source-Neofectch With modifications

RED="\033[0;31m"
WHITE="\033[0;37m"
BOLD="\033[0;1m"
echo "${BOLD}

            ${RED}.-/+oossssoo+/-.                 
         :+ssssssssssssssssss+:             
      -+ssssssssssssssssssyyssss+-           
    .ossssssssssssssssss${WHITE}dMMMNy${RED}sssso.        
   /sssssssssss${WHITE}hdmmNNmmyNMMMMh${RED}ssssss/        
  +sssssssss${WHITE}hm${RED}yd${WHITE}MMMMMMMNddddy${RED}ssssssss+       
 /ssssssss${WHITE}hNMMM${RED}yh${WHITE}hyyyyhmNMMMNh${RED}ssssssss/       
.ssssssss${WHITE}dMMMNh${RED}ssssssssss${WHITE}hNMMMd${RED}ssssssss.     
+ssss${WHITE}hhhyNMMNy${RED}ssssssssssss${WHITE}yNMMMy${RED}sssssss+      
oss${WHITE}yNMMMNyMMh${RED}ssssssssssssss${WHITE}hmmmh${RED}ssssssso      
oss${WHITE}yNMMMNyMMh${RED}sssssssssssssshmmmhssssssso     
+ssss${WHITE}hhhyNMMNy${RED}ssssssssssss${WHITE}yNMMMy${RED}sssssss+      
.ssssssss${WHITE}dMMMNh${RED}ssssssssss${WHITE}hNMMMd${RED}ssssssss.      
 /ssssssss${WHITE}hNMMM${RED}yh${WHITE}hyyyyhdNMMMNh${RED}ssssssss/       
  +sssssssss${WHITE}dm${RED}yd${WHITE}MMMMMMMMddddy${RED}ssssssss+       
   /sssssssssss${WHITE}hdmNNNNmyNMMMMh${RED}ssssss/         
    .ossssssssssssssssss${WHITE}dMMMNy${RED}sssso.          
      -+sssssssssssssssss${WHITE}yyy${RED}ssss+-           
         :+ssssssssssssssssss+: 
            .-/+oossssoo+/-.                                 
                                                               
"
